#!/bin/bash
#
# Author      : Kuba Sejdak <kuba.sejdak@gmail.com>
# Description : Starts debugging session for STM32Discovery.

QUADCOPTER_PATH="/home/kuba/Projects/quadcopter"
FLIGHTCONTROLLER_FIRMWARE_PATH="$QUADCOPTER_PATH/bin/debug/flight-controller.elf"
FLIGHTCONTROLLER_GDBINIT_PATH="$QUADCOPTER_PATH/flight-controller/board/stm32f4_discovery/stm32f4_discovery.gdbinit"

arm-none-eabi-gdb --tui $FLIGHTCONTROLLER_FIRMWARE_PATH -x $FLIGHTCONTROLLER_GDBINIT_PATH
