#!/bin/bash
#
# Author      : Kuba Sejdak <kuba.sejdak@gmail.com>
# Description : Flashes new firmware using OpenOCD and immediately starts debugging session.

FLIGHTCONTROLLER_PATH="/home/kuba/Projects/quadcopter/flight-controller"
FLIGHTCONTROLLER_FIRMWARE_PATH="$FLIGHTCONTROLLER_PATH/bin/stm32f4_discovery/Debug/flight-controller.elf"

openocd -f /usr/share/openocd/scripts/board/stm32f4discovery.cfg -c init \
                                                                 -c targets \
                                                                 -c "halt" \
                                                                 -c "flash write_image erase $FLIGHTCONTROLLER_FIRMWARE_PATH" \
                                                                 -c "verify_image $FLIGHTCONTROLLER_FIRMWARE_PATH" \
                                                                 -c "init" \
                                                                 -c "reset halt"
