#!/bin/bash
#
# Author      : Kuba Sejdak <kuba.sejdak@gmail.com>
# Description : Flashes new firmware using OpenOCD.

QUADCOPTER_PATH="/home/kuba/Projects/quadcopter"
FLIGHTCONTROLLER_FIRMWARE_PATH="$QUADCOPTER_PATH/bin/debug/flight-controller.elf"

openocd -f /usr/share/openocd/scripts/board/stm32f4discovery.cfg -c init \
                                                                 -c targets \
                                                                 -c "halt" \
                                                                 -c "flash write_image erase $FLIGHTCONTROLLER_FIRMWARE_PATH" \
                                                                 -c "verify_image $FLIGHTCONTROLLER_FIRMWARE_PATH" \
                                                                 -c "reset halt" \
                                                                 -c shutdown
